# Generated by Django 5.2.17 on 2026-09-20 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای تراکنش')),
                ('gateway', models.CharField(default='sandbox', max_length=50, verbose_name='درگاه پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ تراکنش (تومان)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESSFUL', 'موفق و تایید شده'), ('FAILED', 'ناموفق با خطا'), ('CANCELLED', 'انصراف توسط خریدار')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت پرداخت')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری / مرجع بانکی (RRN)')),
                ('card_pan_masked', models.CharField(blank=True, max_length=30, verbose_name='شماره کارت ماسک\u200cشده')),
                ('error_message', models.TextField(blank=True, verbose_name='علت خطا یا پیام درگاه')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP کاربر')),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='کلید عدم تکرار (Idempotency Key)')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اعتبارسنجی نهایی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
