# Generated by Django 5.2.17 on 2026-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='زیرعنوان / توضیحات کوتاه')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('link_url', models.CharField(default='/shop/', max_length=300, verbose_name='آدرس لینک')),
                ('position', models.CharField(choices=[('hero', 'اسلایدر هیرو (بالای صفحه اصلی)'), ('middle_dual_1', 'بنر میانی دوتایی - سمت راست'), ('middle_dual_2', 'بنر میانی دوتایی - سمت چپ'), ('special_offer', 'بنر پیشنهاد ویژه عریض'), ('sidebar', 'بنر ستون کناری')], default='hero', max_length=30, verbose_name='موقعیت نمایش')),
                ('button_text', models.CharField(default='مشاهده و خرید', max_length=50, verbose_name='متن دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر و اسلایدر',
                'verbose_name_plural': 'بنرها و اسلایدرها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل مشترک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('site_name', models.CharField(default='فروشگاه اینترنتی مدرن', max_length=150, verbose_name='نام فروشگاه')),
                ('site_tagline', models.CharField(default='تجربه خریدی مطمئن، سریع و لذت\u200cبخش', max_length=250, verbose_name='شعار فروشگاه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگوی فروشگاه')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاوآیکون')),
                ('phone', models.CharField(default='021-88889999', max_length=30, verbose_name='شماره تماس پشتیبانی')),
                ('email', models.EmailField(default='support@shop.local', max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('address', models.CharField(default='تهران، خیابان ولیعصر، برج فناوری، طبقه ۴', max_length=300, verbose_name='آدرس دفتر مرکزی')),
                ('working_hours', models.CharField(default='شنبه تا چهارشنبه ۹ الی ۱۸ - پنجشنبه ۹ الی ۱۴', max_length=100, verbose_name='ساعات پاسخگویی')),
                ('currency', models.CharField(default='تومان', max_length=20, verbose_name='واحد پول')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=0, default=500000, max_digits=12, verbose_name='حداقل خرید برای ارسال رایگان (تومان)')),
                ('standard_shipping_cost', models.DecimalField(decimal_places=0, default=45000, max_digits=12, verbose_name='هزینه ارسال پیش\u200cفرض (تومان)')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', verbose_name='لینک اینستاگرام')),
                ('telegram_url', models.URLField(blank=True, default='https://t.me', verbose_name='لینک تلگرام')),
                ('about_us', models.TextField(default='فروشگاه اینترنتی ما با هدف ارائه برترین محصولات با اصالت تضمین\u200cشده و بهترین قیمت آغاز به کار نموده است.', verbose_name='درباره ما')),
                ('privacy_policy', models.TextField(default='ما به حریم خصوصی تمامی کاربران احترام می\u200cگذاریم و اطلاعات شما را با بالاترین استانداردهای امنیتی محافظت می\u200cکنیم.', verbose_name='سیاست حریم خصوصی')),
                ('terms_and_conditions', models.TextField(default='استفاده از خدمات این فروشگاه به معنای پذیرش کامل قوانین و مقررات تجارت الکترونیک است.', verbose_name='قوانین و شرایط')),
                ('shipping_policy', models.TextField(default='ارسال سفارشات تهران با پیک اکسپرس و شهرستان\u200cها با پست پیشتاز و تیپاکس ظرف ۲۴ تا ۴۸ ساعت کاری انجام می\u200cپذیرد.', verbose_name='رویه ارسال')),
                ('returns_policy', models.TextField(default='امکان مرجوعی کالا تا ۷ روز پس از تحویل در صورت عدم باز شدن پلمپ یا اشکال فنی کالا وجود دارد.', verbose_name='رویه مرجوعی کالا')),
                ('cookie_policy', models.TextField(default='این وب\u200cسایت برای بهبود تجربه کاربری و حفظ وضعیت سبد خرید از کوکی\u200cهای استاندارد استفاده می\u200cکند.', verbose_name='سیاست کوکی\u200cها')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
