# Generated by Django 5.2.17 on 2026-09-25 12:26

import core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=core.crypto.EncryptedTextField(verbose_name='متن پیام (رمزنگاری\u200cشده)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=core.crypto.EncryptedCharField(blank=True, max_length=500, verbose_name='شماره تماس (رمزنگاری\u200cشده)'),
        ),
    ]
