# -*- coding: utf-8 -*-
"""
EMBER · Master catalog content for the shop rebuild.
Consumed by:
  - management command `rebuild_catalog`   (categories, brands, products, reviews, variants)
  - script `gen_images.py`                 (image prompts)
Price unit: Toman. days_old = product age in days (used for auto "جدید" badge <= 7 days).
"""

IMG_STYLE = ("Professional e-commerce studio product photograph of {subject}, centered composition on a "
             "seamless light grey studio background, soft diffused lighting, subtle soft shadow beneath, "
             "ultra clean minimal, photorealistic, high detail, no text, no watermark, no logos, no branding")

IMG_STYLE_ALT = ("Professional e-commerce studio product photograph of {subject}, three-quarter angle view, "
                 "on a seamless light grey studio background, soft diffused lighting, subtle shadow, "
                 "photorealistic, ultra clean minimal, no text, no watermark, no logos, no branding")

CATEGORIES = [
    {"name": "کالای دیجیتال", "slug": "digital", "children": [
        {"name": "موبایل", "slug": "mobile", "children": [
            {"name": "گوشی موبایل", "slug": "mobile-phones"},
            {"name": "لوازم جانبی موبایل", "slug": "mobile-accessories"},
        ]},
        {"name": "لپ‌تاپ و کامپیوتر", "slug": "computers", "children": [
            {"name": "لپ‌تاپ", "slug": "laptops"},
            {"name": "مانیتور", "slug": "monitors"},
            {"name": "کیبورد و ماوس", "slug": "keyboard-mouse"},
            {"name": "قطعات و ذخیره‌سازی", "slug": "pc-parts"},
        ]},
        {"name": "تبلت و کتابخوان", "slug": "tablets", "children": [
            {"name": "تبلت", "slug": "tablets-main"},
            {"name": "کتابخوان", "slug": "e-readers"},
        ]},
        {"name": "صوتی و تصویری", "slug": "av", "children": [
            {"name": "هدفون و هدست", "slug": "headphones"},
            {"name": "هدفون بی‌سیم", "slug": "earbuds"},
            {"name": "اسپیکر", "slug": "speakers"},
            {"name": "تلویزیون و پروژکتور", "slug": "tv-projector"},
        ]},
        {"name": "دوربین و فیلم‌برداری", "slug": "cameras", "children": [
            {"name": "دوربین", "slug": "cameras-main"},
            {"name": "دوربین اکشن", "slug": "action-cams"},
        ]},
        {"name": "مودم و شبکه", "slug": "network"},
    ]},
    {"name": "ساعت و پوشیدنی هوشمند", "slug": "wearables", "children": [
        {"name": "ساعت هوشمند", "slug": "smartwatches"},
        {"name": "مچ‌بند هوشمند", "slug": "fitness-bands"},
        {"name": "لوازم پوشیدنی", "slug": "wearable-accessories"},
    ]},
    {"name": "گیمینگ", "slug": "gaming", "children": [
        {"name": "کنسول بازی", "slug": "consoles"},
        {"name": "دسته و لوازم جانبی", "slug": "gaming-accessories"},
        {"name": "تجهیزات گیمینگ", "slug": "gaming-gear"},
        {"name": "صندلی گیمینگ", "slug": "gaming-chairs"},
    ]},
    {"name": "لوازم خانگی", "slug": "home-appliances", "children": [
        {"name": "آشپزخانه", "slug": "kitchen", "children": [
            {"name": "قهوه‌ساز و چای‌ساز", "slug": "coffee-tea"},
            {"name": "غذاساز و مخلوط‌کن", "slug": "blenders"},
            {"name": "سرخ‌کن و مایکروویو", "slug": "fryers-microwaves"},
            {"name": "لوازم برقی کوچک", "slug": "small-electric"},
        ]},
        {"name": "شست‌وشو", "slug": "laundry", "children": [
            {"name": "ماشین لباسشویی", "slug": "washing-machines"},
            {"name": "ظرفشویی", "slug": "dishwashers"},
        ]},
        {"name": "نظافت و پاکیزگی", "slug": "cleaning", "children": [
            {"name": "جاروبرقی", "slug": "vacuums"},
            {"name": "جاروی رباتیک", "slug": "robot-vacuums"},
        ]},
        {"name": "آب و هوا", "slug": "air-water", "children": [
            {"name": "تصفیه هوا", "slug": "air-purifiers"},
            {"name": "تصفیه آب", "slug": "water-purifiers"},
            {"name": "پنکه و بخور", "slug": "fans-humidifiers"},
        ]},
    ]},
    {"name": "زیبایی و سلامت", "slug": "beauty-health", "children": [
        {"name": "مراقبت مو و ریش", "slug": "hair-care", "children": [
            {"name": "سشوار و اتو مو", "slug": "hair-stylers"},
            {"name": "ریش‌تراش و تریمر", "slug": "shavers"},
        ]},
        {"name": "مراقبت پوست", "slug": "skin-care"},
        {"name": "سلامت و ماساژ", "slug": "wellness", "children": [
            {"name": "ماساژور", "slug": "massagers"},
            {"name": "ترازو و ابزار سلامت", "slug": "health-monitors"},
        ]},
    ]},
    {"name": "مد و پوشاک", "slug": "fashion", "children": [
        {"name": "مردانه", "slug": "mens-fashion"},
        {"name": "زنانه", "slug": "womens-fashion"},
        {"name": "کیف و کوله", "slug": "bags"},
        {"name": "اکسسوری", "slug": "fashion-accessories"},
    ]},
    {"name": "ورزش و سفر", "slug": "sports-travel", "children": [
        {"name": "تجهیزات ورزشی", "slug": "sports-gear"},
        {"name": "دوچرخه و اسکوتر", "slug": "bikes-scooters"},
        {"name": "کمپینگ و کوهنوردی", "slug": "camping"},
        {"name": "چمدان و سفر", "slug": "luggage"},
    ]},
    {"name": "خودرو و ابزار", "slug": "auto-tools", "children": [
        {"name": "لوازم خودرو", "slug": "car-accessories"},
        {"name": "ابزار برقی", "slug": "power-tools"},
        {"name": "ابزار دستی", "slug": "hand-tools"},
    ]},
    {"name": "خانه و آشپزخانه", "slug": "home-kitchen", "children": [
        {"name": "دکور و روشنایی", "slug": "decor-lighting"},
        {"name": "لوازم آشپزخانه", "slug": "kitchenware"},
        {"name": "روتختی و حمام", "slug": "bedding-bath"},
    ]},
    {"name": "سوپرمارکت", "slug": "grocery", "children": [
        {"name": "خوراکی و تنقلات", "slug": "snacks"},
        {"name": "نوشیدنی", "slug": "beverages"},
        {"name": "شوینده و بهداشتی", "slug": "household-clean"},
    ]},
    {"name": "کتاب و لوازم‌التحریر", "slug": "books-stationery", "children": [
        {"name": "کتاب", "slug": "books"},
        {"name": "لوازم‌التحریر", "slug": "stationery"},
        {"name": "بازی فکری و پازل", "slug": "puzzles"},
    ]},
    {"name": "کودک و اسباب‌بازی", "slug": "kids-toys", "children": [
        {"name": "اسباب‌بازی", "slug": "toys"},
        {"name": "مراقبت کودک", "slug": "baby-care"},
    ]},
]

BRANDS = [
    ("اپل", "apple"), ("سامسونگ", "samsung"), ("شیائومی", "xiaomi"), ("سونی", "sony"),
    ("جی‌بی‌ال", "jbl"), ("بوز", "bose"), ("انکر", "anker"), ("لاجیتک", "logitech"),
    ("ریزر", "razer"), ("فیلیپس", "philips"), ("بوش", "bosch"), ("دلونگی", "delonghi"),
    ("دایسون", "dyson"), ("ایسوس", "asus"), ("لنوو", "lenovo"), ("اچ‌پی", "hp"),
    ("کانن", "canon"), ("گوپرو", "gopro"), ("پلی‌استیشن", "playstation"), ("نایک", "nike"),
    ("گارمین", "garmin"), ("براون", "braun"), ("پاناسونیک", "panasonic"), ("کروز", "crouse"),
]

PRODUCTS = [
    # ---------------- digital / mobile-phones ----------------
    {"slug": "iphone-16-pro-max", "name": "گوشی موبایل اپل مدل iPhone 16 Pro Max ظرفیت ۲۵۶ گیگابایت",
     "category": "mobile-phones", "brand": "apple", "price": 92000000, "sale": 88900000, "stock": 14,
     "featured": True, "bestseller": True, "days_old": 35, "img_count": 2,
     "subject": "a modern flagship smartphone in titanium grey with a large edge-to-edge display",
     "short": "پرچمدار اپل با تراشه A18 Pro و دوربین ۴۸ مگاپیکسلی",
     "desc": "iPhone 16 Pro Max با قاب تیتانیومی، نمایشگر Super Retina XDR و تراشه A18 Pro سریع‌ترین تجربه آیفون را ارائه می‌دهد. دوربین سه‌گانه این گوشی با فیلم‌برداری ۴K/۱۲۰ فریم، انتخابی حرفه‌ای برای عکاسی و تولید محتواست.",
     "specs": [("نمایشگر", "۶.۹ اینچ Super Retina XDR"), ("تراشه", "Apple A18 Pro"), ("حافظه", "۲۵۶ گیگابایت"), ("دوربین", "۴۸+۱۲+۱۲ مگاپیکسل"), ("باتری", "تا ۳۳ ساعت پخش ویدیو")]},
    {"slug": "galaxy-s24-ultra", "name": "گوشی موبایل سامسونگ مدل Galaxy S24 Ultra ظرفیت ۲۵۶ گیگابایت",
     "category": "mobile-phones", "brand": "samsung", "price": 58500000, "sale": 54900000, "stock": 18,
     "featured": True, "bestseller": True, "days_old": 50, "img_count": 2,
     "subject": "a modern premium android smartphone with a stylus and quad camera module",
     "short": "پرچمدار سامسونگ با قلم S Pen و دوربین ۲۰۰ مگاپیکسلی",
     "desc": "Galaxy S24 Ultra با نمایشگر تخت ۶.۸ اینچی، قاب تیتانیومی و قابلیت‌های هوش مصنوعی Galaxy AI همراه است. دوربین ۲۰۰ مگاپیکسلی و زوم اپتیکال ۵ برابری، آن را به بهترین انتخاب برای عکاسی تبدیل می‌کند.",
     "specs": [("نمایشگر", "۶.۸ اینچ Dynamic AMOLED 2X"), ("تراشه", "Snapdragon 8 Gen 3"), ("حافظه", "۲۵۶ گیگابایت"), ("دوربین", "۲۰۰ مگاپیکسل"), ("ویژگی", "S Pen همراه")]},
    {"slug": "xiaomi-14t-pro", "name": "گوشی موبایل شیائومی مدل 14T Pro ظرفیت ۵۱۲ گیگابایت",
     "category": "mobile-phones", "brand": "xiaomi", "price": 32800000, "stock": 22,
     "featured": False, "bestseller": True, "days_old": 6, "img_count": 1,
     "subject": "a sleek modern smartphone with a minimalist design and triple camera",
     "short": "قدرتمند و مقرون‌به‌صرفه با لنزهای Leica",
     "desc": "شیائومی 14T Pro با تراشه Dimensity 9300+ و لنزهای Leica، عملکرد پرچمدار را با قیمتی رقابتی ارائه می‌دهد. شارژ سریع ۱۲۰ واتی در کمتر از ۲۰ دقیقه باتری را کامل می‌کند.",
     "specs": [("نمایشگر", "۶.۶۷ اینچ AMOLED ۱۴۴ هرتز"), ("تراشه", "Dimensity 9300+"), ("حافظه", "۵۱۲ گیگابایت"), ("دوربین", "۵۰ مگاپیکسل Leica"), ("شارژ", "۱۲۰ وات")]},
    {"slug": "anker-powerbank-20000", "name": "پاوربانک انکر مدل PowerCore 20000 میلی‌آمپر با شارژ سریع",
     "category": "mobile-accessories", "brand": "anker", "price": 1890000, "stock": 60,
     "featured": False, "bestseller": True, "days_old": 60, "img_count": 1,
     "subject": "a compact black power bank with digital display and USB ports",
     "short": "۲۰۰۰۰ میلی‌آمپر با نمایشگر دیجیتال و شارژ ۳۰ واتی",
     "desc": "پاوربانک ۲۰۰۰۰ میلی‌آمپری انکر با دو پورت USB-C و USB-A، سه دستگاه را هم‌زمان شارژ می‌کند. نمایشگر دیجیتال، درصد شارژ باقی‌مانده را دقیق نشان می‌دهد.",
     "specs": [("ظرفیت", "۲۰۰۰۰ میلی‌آمپر ساعت"), ("توان", "۳۰ وات"), ("پورت‌ها", "۲×USB-C و ۲×USB-A"), ("وزن", "۳۴۵ گرم")]},
    {"slug": "anker-charger-65w-gan", "name": "شارژر دیواری انکر مدل 65W GaN سه‌پورت",
     "category": "mobile-accessories", "brand": "anker", "price": 1450000, "stock": 75,
     "featured": False, "bestseller": False, "days_old": 12, "img_count": 1,
     "subject": "a small white GaN wall charger with three ports",
     "short": "شارژر فشرده GaN برای لپ‌تاپ، موبایل و تبلت",
     "desc": "شارژر ۶۵ واتی انکر با فناوری GaN در ابعادی کوچک‌تر از شارژرهای معمول، توان کافی برای شارژ هم‌زمان لپ‌تاپ و گوشی را دارد.",
     "specs": [("توان", "۶۵ وات"), ("پورت‌ها", "۲×USB-C + ۱×USB-A"), ("فناوری", "GaN II"), ("سازگاری", "لپ‌تاپ، موبایل، تبلت")]},
    # ---------------- computers ----------------
    {"slug": "macbook-air-m3-13", "name": "لپ‌تاپ اپل مدل MacBook Air 13 اینچ M3 ظرفیت ۵۱۲ گیگابایت",
     "category": "laptops", "brand": "apple", "price": 74500000, "sale": 71900000, "stock": 9,
     "featured": True, "bestseller": False, "days_old": 45, "img_count": 2,
     "subject": "a slim silver aluminum laptop slightly open on a minimal stand",
     "short": "سبک، بی‌صدا و با باتری ۱۸ ساعته",
     "desc": "مک‌بوک ایر M3 با بدنه آلومینیومی ۱.۲۴ کیلوگرمی، برای کار روزمره و حرفه‌ای سبک ایده‌آل است. تراشه M3 عملکرد چشمگیری با مصرف انرژی بهینه ارائه می‌دهد.",
     "specs": [("نمایشگر", "۱۳.۶ اینچ Liquid Retina"), ("تراشه", "Apple M3"), ("رم", "۸ گیگابایت"), ("حافظه", "۵۱۲ گیگابایت SSD"), ("باتری", "تا ۱۸ ساعت")]},
    {"slug": "asus-zenbook-14-oled", "name": "لپ‌تاپ ایسوس مدل Zenbook 14 OLED اولترا ۷",
     "category": "laptops", "brand": "asus", "price": 52000000, "stock": 11,
     "featured": False, "bestseller": False, "days_old": 30, "img_count": 1,
     "subject": "a modern thin laptop with a glowing color-rich screen",
     "short": "نمایشگر OLED با پردازنده اولترا ۷",
     "desc": "زن‌بوک ۱۴ OLED با صفحه نمایش ۳K OLED و پردازنده Intel Core Ultra 7، ترکیبی از زیبایی و قدرت برای کاربران حرفه‌ای است.",
     "specs": [("نمایشگر", "۱۴ اینچ ۲.۸K OLED"), ("پردازنده", "Core Ultra 7"), ("رم", "۱۶ گیگابایت"), ("حافظه", "۱ ترابایت SSD"), ("وزن", "۱.۲۸ کیلوگرم")]},
    {"slug": "samsung-odyssey-g5-27", "name": "مانیتور گیمینگ سامسونگ مدل Odyssey G5 سایز ۲۷ اینچ",
     "category": "monitors", "brand": "samsung", "price": 15900000, "stock": 16,
     "featured": False, "bestseller": False, "days_old": 70, "img_count": 1,
     "subject": "a curved widescreen gaming monitor on a minimal desk stand",
     "short": "نمایشگر منحنی ۱۴۴ هرتز QHD",
     "desc": "مانیتور اودیسه G5 با پنل QHD، نرخ تازه‌سازی ۱۴۴ هرتز و پشتیبانی AMD FreeSync Premium، تجربه بازی روانی ارائه می‌دهد.",
     "specs": [("اندازه", "۲۷ اینچ"), ("رزولوشن", "QHD 2560×1440"), ("نرخ تازه‌سازی", "۱۴۴ هرتز"), ("پنل", "VA منحنی ۱۰۰۰R")]},
    {"slug": "logitech-mx-master-3s", "name": "ماوس بی‌سیم لاجیتک مدل MX Master 3S",
     "category": "keyboard-mouse", "brand": "logitech", "price": 3950000, "sale": 3590000, "stock": 40,
     "featured": False, "bestseller": True, "days_old": 55, "img_count": 1,
     "subject": "an ergonomic graphite wireless mouse with thumb wheel",
     "short": "ماوس حرفه‌ای با سنسور ۸۰۰۰ DPI و اسکرول MagSpeed",
     "desc": "MX Master 3S با طراحی ارگونومیک، کلیک‌های سایلنت و اسکرول مغناطیسی MagSpeed، انتخاب اول کاربران حرفه‌ای است.",
     "specs": [("سنسور", "۸۰۰۰ DPI"), ("اتصال", "Bluetooth / USB Receiver"), ("باتری", "تا ۷۰ روز"), ("ویژگی", "اسکرول MagSpeed")]},
    {"slug": "logitech-mx-keys-mini", "name": "کیبورد مکانیکال لاجیتک مدل MX Keys Mini",
     "category": "keyboard-mouse", "brand": "logitech", "price": 4700000, "stock": 25,
     "featured": False, "bestseller": False, "days_old": 40, "img_count": 1,
     "subject": "a compact wireless keyboard with backlit keys",
     "short": "کیبورد فشرده با نور پس‌زمینه و اتصال چند دستگاه",
     "desc": "MX Keys Mini با کلیدهای کره‌ای شکل و نور هوشمند پس‌زمینه، تایپی راحت در ابعادی جمع‌وجور ارائه می‌دهد. سوییچ بین سه دستگاه با یک کلید.",
     "specs": [("چیدمان", "فشرده بدون Numpad"), ("اتصال", "Bluetooth + USB"), ("نور", "پس‌زمینه هوشمند"), ("باتری", "تا ۱۰ روز با نور روشن")]},
    {"slug": "samsung-ssd-t7-1tb", "name": "حافظه SSD اکسترنال سامسونگ مدل T7 ظرفیت ۱ ترابایت",
     "category": "pc-parts", "brand": "samsung", "price": 4100000, "stock": 33,
     "featured": False, "bestseller": False, "days_old": 65, "img_count": 1,
     "subject": "a slim metallic portable SSD with usb-c cable",
     "short": "SSD پرتابل با سرعت ۱۰۵۰ مگابایت بر ثانیه",
     "desc": "سامسونگ T7 با سرعت خواندن ۱۰۵۰ مگابایت بر ثانیه، انتقال فایل‌های حجیم را در ثانیه‌ها ممکن می‌کند. بدنه فلزی مقاوم و رمزنگاری سخت‌افزاری AES 256 بیتی دارد.",
     "specs": [("ظرفیت", "۱ ترابایت"), ("سرعت خواندن", "۱۰۵۰ مگابایت/ثانیه"), ("اتصال", "USB 3.2 Gen 2"), ("امنیت", "رمزنگاری AES 256-bit")]},
    # ---------------- tablets ----------------
    {"slug": "ipad-air-11-m2", "name": "تبلت اپل مدل iPad Air 11 اینچ M2 ظرفیت ۱۲۸ گیگابایت",
     "category": "tablets-main", "brand": "apple", "price": 42500000, "stock": 13,
     "featured": True, "bestseller": False, "days_old": 4, "img_count": 2,
     "subject": "a modern slim tablet in blue with a stylus lying beside it",
     "short": "سبک و قدرتمند با تراشه M2",
     "desc": "آیپد ایر M2 با نمایشگر Liquid Retina و پشتیبانی از Apple Pencil Pro، ترکیبی از خلاقیت و کارایی است. مناسب طراحی، یادداشت‌برداری و سرگرمی.",
     "specs": [("نمایشگر", "۱۱ اینچ Liquid Retina"), ("تراشه", "Apple M2"), ("حافظه", "۱۲۸ گیگابایت"), ("دوربین", "۱۲ مگاپیکسل"), ("ویژگی", "پشتیبانی Apple Pencil Pro")]},
    {"slug": "galaxy-tab-s9-fe", "name": "تبلت سامسونگ مدل Galaxy Tab S9 FE ظرفیت ۱۲۸ گیگابایت",
     "category": "tablets-main", "brand": "samsung", "price": 18900000, "stock": 17,
     "featured": False, "bestseller": False, "days_old": 26, "img_count": 1,
     "subject": "a modern tablet with a stylus in a soft color",
     "short": "تبلت میان‌رده با قلم S Pen همراه",
     "desc": "گلکسی تب S9 FE با نمایشگر ۱۰.۹ اینچی و قلم S Pen، گزینه‌ای کامل برای دانشجویان و کاربران روزمره است. مقاومت IP68 در برابر آب و گردوغبار دارد.",
     "specs": [("نمایشگر", "۱۰.۹ اینچ TFT"), ("حافظه", "۱۲۸ گیگابایت"), ("باتری", "۱۰۰۹۰ میلی‌آمپر"), ("ویژگی", "S Pen همراه")]},
    # ---------------- av ----------------
    {"slug": "airpods-pro-2", "name": "هندزفری بی‌سیم اپل مدل AirPods Pro نسخه ۲ با پورت USB-C",
     "category": "earbuds", "brand": "apple", "price": 18300000, "sale": 16900000, "stock": 30,
     "featured": True, "bestseller": True, "days_old": 42, "img_count": 2,
     "subject": "white premium wireless earbuds with charging case",
     "short": "نویز کنسلینگ فعال و صدای Spatial",
     "desc": "ایرپاد پرو ۲ با تراشه H2، نویز کنسلینگ فعال دو برابر قوی‌تر و صدای فضایی ارائه می‌دهد. کیس شارژ USB-C تا ۳۰ ساعت شارژ نگه می‌دارد.",
     "specs": [("نویز کنسلینگ", "فعال (ANC)"), ("تراشه", "Apple H2"), ("باتری", "تا ۶ ساعت + کیس"), ("اتصال", "USB-C / MagSafe")]},
    {"slug": "sony-wh-1000xm5", "name": "هدفون بی‌سیم سونی مدل WH-1000XM5",
     "category": "headphones", "brand": "sony", "price": 21500000, "stock": 15,
     "featured": True, "bestseller": False, "days_old": 48, "img_count": 2,
     "subject": "premium noise cancelling over-ear headphones in black",
     "short": "بهترین نویز کنسلینگ بازار با باتری ۳۰ ساعته",
     "desc": "هدفون WH-1000XM5 سونی با ۸ میکروفن و دو پردازنده، هوشمندترین نویز کنسلینگ را ارائه می‌دهد. کیفیت صدای Hi-Res با کدک LDAC.",
     "specs": [("نوع", "دور گوشی (Over-Ear)"), ("نویز کنسلینگ", "فعال پیشرفته"), ("باتری", "تا ۳۰ ساعت"), ("کدک", "LDAC / AAC / SBC")]},
    {"slug": "jbl-charge-5", "name": "اسپیکر بلوتوثی جی‌بی‌ال مدل Charge 5",
     "category": "speakers", "brand": "jbl", "price": 8900000, "stock": 26,
     "featured": False, "bestseller": True, "days_old": 80, "img_count": 1,
     "subject": "a rugged cylindrical portable bluetooth speaker",
     "short": "صدای قدرتمند، ضدآب و ۲۰ ساعت پخش",
     "desc": "اسپیکر JBL Charge 5 با درایورهای جدید و رادیاتورهای تقویت بیس، صدایی پرقدرت ارائه می‌دهد. ضدآب IP67 و باتری ۲۰ ساعته برای سفر و طبیعت‌گردی.",
     "specs": [("توان", "۳۰ وات RMS"), ("باتری", "۷۵۰۰ میلی‌آمپر / ۲۰ ساعت"), ("مقاومت", "IP67 ضدآب و گردوغبار"), ("ویژگی", "پاوربانک اضطراری")]},
    {"slug": "xiaomi-tv-a2-55", "name": "تلویزیون هوشمند شیائومی مدل TV A2 سایز ۵۵ اینچ",
     "category": "tv-projector", "brand": "xiaomi", "price": 28400000, "stock": 7,
     "featured": False, "bestseller": False, "days_old": 33, "img_count": 1,
     "subject": "a slim bezel-less smart television on a minimal stand",
     "short": "تلویزیون ۴K با اندروید TV",
     "desc": "تلویزیون شیائومی A2 با نمایشگر ۴K HDR و سیستم اندروید TV، دسترسی به تمام اپلیکیشن‌های استریم را فراهم می‌کند. سه پورت HDMI و Dolby Audio دارد.",
     "specs": [("اندازه", "۵۵ اینچ"), ("رزولوشن", "4K UHD"), ("سیستم", "Android TV"), ("صدا", "Dolby Audio ۲۰ وات")]},
    # ---------------- cameras ----------------
    {"slug": "gopro-hero-12", "name": "دوربین اکشن گوپرو مدل HERO12 Black",
     "category": "action-cams", "brand": "gopro", "price": 24800000, "sale": 23200000, "stock": 10,
     "featured": False, "bestseller": False, "days_old": 5, "img_count": 2,
     "subject": "a rugged action camera on a small tripod mount, front view",
     "short": "ویدیو ۵.۳K با لرزشگیر HyperSmooth 6.0",
     "desc": "گوپرو HERO12 با لرزشگیر HyperSmooth 6.0 و ویدیو ۵.۳K، تصاویری پایدار در سخت‌ترین شرایط ثبت می‌کند. باتری Enduro پخش تا ۷۰ دقیقه را ممکن می‌سازد.",
     "specs": [("ویدیو", "۵.۳K ۶۰fps"), ("لرزشگیر", "HyperSmooth 6.0"), ("مقاومت", "ضدآب تا ۱۰ متر"), ("باتری", "Enduro")]},
    {"slug": "canon-eos-r50", "name": "دوربین بدون آینه کانن مدل EOS R50 همراه لنز 18-45mm",
     "category": "cameras-main", "brand": "canon", "price": 39800000, "stock": 6,
     "featured": False, "bestseller": False, "days_old": 60, "img_count": 1,
     "subject": "a compact mirrorless camera in black with a kit lens on a clean surface",
     "short": "دوربین ۲۴ مگاپیکسل سبک برای تولید محتوا",
     "desc": "کانن EOS R50 با سنسور APS-C ۲۴.۲ مگاپیکسلی و فوکوس خودکار Dual Pixel، دوربینی سبک برای ولاگ و عکاسی روزمره است. ویدیو ۴K بدون کراپ ثبت می‌کند.",
     "specs": [("سنسور", "APS-C ۲۴.۲ مگاپیکسل"), ("ویدیو", "4K 30fps"), ("فوکوس", "Dual Pixel CMOS AF II"), ("وزن", "۳۷۵ گرم")]},
    # ---------------- wearables ----------------
    {"slug": "apple-watch-ultra-2", "name": "ساعت هوشمند اپل مدل Watch Ultra 2 سایز ۴۹ میلی‌متری",
     "category": "smartwatches", "brand": "apple", "price": 46900000, "stock": 12,
     "featured": True, "bestseller": False, "days_old": 38, "img_count": 2,
     "subject": "a rugged titanium smartwatch with an orange ocean band",
     "short": "مقاوم و حرفه‌ای برای ورزش و ماجراجویی",
     "desc": "اپل واچ اولترا ۲ با جنس تیتانیوم و نمایشگر ۳۰۰۰ نیتی، روشن‌ترین نمایشگر اپل واچ را دارد. مناسب غواصی، کوهنوردی و ورزش‌های حرفه‌ای با باتری ۳۶ ساعته.",
     "specs": [("صفحه", "۴۹ میلی‌متر تیتانیوم"), ("نمایشگر", "۳۰۰۰ نیت"), ("باتری", "تا ۳۶ ساعت"), ("مقاومت", "WR100 / EN13319")]},
    {"slug": "galaxy-watch-6-classic", "name": "ساعت هوشمند سامسونگ مدل Galaxy Watch 6 Classic سایز ۴۷ میلی‌متری",
     "category": "smartwatches", "brand": "samsung", "price": 15700000, "stock": 20,
     "featured": False, "bestseller": False, "days_old": 2, "img_count": 1,
     "subject": "a classic round smartwatch with a rotating bezel",
     "short": "قاب چرخان کلاسیک با پایش سلامت پیشرفته",
     "desc": "گلکسی واچ ۶ کلاسیک با قاب چرخان و طراحی کلاسیک، پایش خواب، ضربان قلب و ترکیب بدن را دقیق انجام می‌دهد. با Wear OS، اپلیکیشن‌های متنوعی نصب می‌شود.",
     "specs": [("صفحه", "۴۷ میلی‌متر"), ("نمایشگر", "Super AMOLED"), ("باتری", "۴۲۵ میلی‌آمپر"), ("ویژگی", "قاب چرخان فیزیکی")]},
    {"slug": "xiaomi-smart-band-9", "name": "مچ‌بند هوشمند شیائومی مدل Smart Band 9",
     "category": "fitness-bands", "brand": "xiaomi", "price": 2890000, "stock": 55,
     "featured": False, "bestseller": True, "days_old": 25, "img_count": 1,
     "subject": "a slim modern fitness band with a bright amoled display",
     "short": "۲۱ روز باتری با نمایشگر AMOLED",
     "desc": "مچ‌بند هوشمند شیائومی با نمایشگر AMOLED ۱.۶۲ اینچی و ۲۰۰ حالت ورزشی، سلامتی شما را ۲۴ ساعته پایش می‌کند. تا ۲۱ روز با یک بار شارژ کار می‌کند.",
     "specs": [("نمایشگر", "۱.۶۲ اینچ AMOLED"), ("باتری", "تا ۲۱ روز"), ("حالت‌های ورزشی", "+۲۰۰ حالت"), ("مقاومت", "۵ ATM")]},
    # ---------------- gaming ----------------
    {"slug": "playstation-5-slim", "name": "کنسول بازی سونی مدل PlayStation 5 Slim نسخه دیسک‌خور",
     "category": "consoles", "brand": "playstation", "price": 39500000, "sale": 37900000, "stock": 8,
     "featured": True, "bestseller": True, "days_old": 3, "img_count": 2,
     "subject": "a modern white game console standing upright with a wireless controller beside it",
     "short": "نسل جدید بازی با کنترلر DualSense",
     "desc": "پلی‌استیشن ۵ اسلیم با حافظه ۱ ترابایتی و درایو بلوری، تجربه بازی ۴K و ۱۲۰ فریم را ارائه می‌دهد. کنترلر DualSense با بازخورد لمسی، حس بازی را تغییر می‌دهد.",
     "specs": [("حافظه", "۱ ترابایت SSD"), ("خروجی", "4K تا ۱۲۰ فریم"), ("درایو", "بلوری ۴K"), ("کنترلر", "DualSense Wireless")]},
    {"slug": "dualsense-controller", "name": "دسته بازی سونی مدل DualSense Wireless برای PS5",
     "category": "gaming-accessories", "brand": "sony", "price": 3850000, "stock": 42,
     "featured": False, "bestseller": True, "days_old": 44, "img_count": 1,
     "subject": "a futuristic white game controller with black accents",
     "short": "بازخورد لمسی و ماشه‌های تطبیقی",
     "desc": "دسته DualSense با بازخورد لمسی دوگانه و ماشه‌های تطبیقی، تجربه‌ای متفاوت از بازی ارائه می‌دهد. میکروفن داخلی و دکمه Create دارد.",
     "specs": [("اتصال", "بی‌سیم Bluetooth"), ("باتری", "داخلی قابل شارژ"), ("ویژگی", "هادپتیک + ماشه تطبیقی"), ("سازگاری", "PS5 / PC")]},
    {"slug": "razer-blackwidow-v4", "name": "کیبورد مکانیکال گیمینگ ریزر مدل BlackWidow V4 X",
     "category": "gaming-gear", "brand": "razer", "price": 6200000, "stock": 15,
     "featured": False, "bestseller": False, "days_old": 52, "img_count": 1,
     "subject": "a black mechanical gaming keyboard with colorful per-key lighting",
     "short": "سوییچ‌های مکانیکی سبز با نورپردازی RGB",
     "desc": "کیبورد گیمینگ بلک‌ویدو V4 X با سوییچ‌های مکانیکی ریزر سبز و نورپردازی Razer Chroma RGB، دقت و سرعت را در بازی تضمین می‌کند.",
     "specs": [("سوییچ", "مکانیکی ریزر سبز"), ("نورپردازی", "Chroma RGB"), ("ویژگی", "Anti-Ghosting کامل"), ("اتصال", "USB")]},
    # ---------------- kitchen ----------------
    {"slug": "delonghi-dedica-ec685", "name": "اسپرسوساز دلونگی مدل Dedica EC685",
     "category": "coffee-tea", "brand": "delonghi", "price": 14900000, "stock": 14,
     "featured": True, "bestseller": False, "days_old": 58, "img_count": 2,
     "subject": "a slim stainless steel espresso machine with a portafilter",
     "short": "اسپرسوساز حرفه‌ای باریک با فشار ۱۵ بار",
     "desc": "اسپرسوساز ددیکا EC685 با بدنه استیل و پمپ ۱۵ بار، کرمای غنی اسپرسو حرفه‌ای را در خانه فراهم می‌کند. سیستم ترموبلاک در ۴۰ ثانیه آماده می‌شود.",
     "specs": [("فشار", "۱۵ بار"), ("سیستم", "ترموبلاک"), ("مخزن آب", "۱.۱ لیتر"), ("ویژگی", "نازل بخار شیردهی")]},
    {"slug": "philips-airfryer-xxl", "name": "سرخ‌کن بدون روغن فیلیپس مدل Airfryer XXL سری ۷",
     "category": "fryers-microwaves", "brand": "philips", "price": 12300000, "sale": 11400000, "stock": 19,
     "featured": False, "bestseller": True, "days_old": 47, "img_count": 1,
     "subject": "a modern black air fryer appliance with a digital panel",
     "short": "ظرفیت ۸ لیتر با فناوری Rapid Air",
     "desc": "سرخ‌کن فیلیپس XXL با ظرفیت ۸ لیتری برای خانواده، غذا را با ۹۰٪ روغن کمتر سرخ می‌کند. فناوری Rapid Air و پنل دیجیتال با ۷ برنامه آماده.",
     "specs": [("ظرفیت", "۸ لیتر"), ("توان", "۲۲۲۵ وات"), ("فناوری", "Rapid Air"), ("برنامه‌ها", "۷ برنامه آماده")]},
    {"slug": "philips-blender-1000w", "name": "مخلوط‌کن فیلیپس مدل HR3655 با پارچ شیشه‌ای ۲ لیتری",
     "category": "blenders", "brand": "philips", "price": 3450000, "stock": 28,
     "featured": False, "bestseller": False, "days_old": 72, "img_count": 1,
     "subject": "a modern electric countertop blender with a glass jar",
     "short": "توان ۱۰۰۰ وات با تیغه‌های ۶ پره",
     "desc": "مخلوط‌کن فیلیپس با موتور ۱۰۰۰ وات و تیغه‌های استیل ۶ پره، مواد سخت مثل یخ را هم یکدست خرد می‌کند. تا ۵ سال گارانتی موتور.",
     "specs": [("توان", "۱۰۰۰ وات"), ("پارچ", "شیشه ۲ لیتر"), ("تیغه", "استیل ۶ پره"), ("ویژگی", "۵ سرعته + Pulse")]},
    {"slug": "bosch-wga252zir", "name": "ماشین لباسشویی بوش مدل WGA252ZIR سری ۶ ظرفیت ۹ کیلوگرم",
     "category": "washing-machines", "brand": "bosch", "price": 41000000, "stock": 5,
     "featured": False, "bestseller": False, "days_old": 90, "img_count": 1,
     "subject": "a modern white front-load washing machine with a dark door",
     "short": "۹ کیلوگرمی با موتور بی‌صدای EcoSilence",
     "desc": "ماشین لباسشویی بوش سری ۶ با ظرفیت ۹ کیلوگرم و موتور EcoSilence Drive، برای خانواده‌های بزرگ ایده‌آل است. برنامه‌های ویژه لکه و ضدحساسیت دارد.",
     "specs": [("ظرفیت", "۹ کیلوگرم"), ("موتور", "EcoSilence Drive"), ("دور موتور", "۱۲۰۰ دور"), ("کلاس", "A+++")]},
    # ---------------- cleaning ----------------
    {"slug": "dyson-v12-detect", "name": "جاروی شارژی دایسون مدل V12 Detect Slim",
     "category": "vacuums", "brand": "dyson", "price": 32900000, "stock": 9,
     "featured": True, "bestseller": False, "days_old": 6, "img_count": 2,
     "subject": "a modern cordless stick vacuum cleaner in gold and silver",
     "short": "لامپ سبز دتکتور و قدرت مکش بالا",
     "desc": "جاروی شارژی دایسون V12 با لیزر Detect Dust نمایش‌دهنده ذرات ریز، مکش ۱۵۰ AW و وزن سبک، نظافت خانه را آسان و لذت‌بخش می‌کند.",
     "specs": [("توان مکش", "۱۵۰ AW"), ("باتری", "تا ۶۰ دقیقه"), ("وزن", "۲.۲ کیلوگرم"), ("ویژگی", "لامپ لیزر Detect")]},
    {"slug": "xiaomi-robot-vacuum-s10", "name": "جاروی رباتیک شیائومی مدل Robot Vacuum S10 Plus",
     "category": "robot-vacuums", "brand": "xiaomi", "price": 11800000, "stock": 21,
     "featured": False, "bestseller": True, "days_old": 30, "img_count": 1,
     "subject": "a round modern robot vacuum cleaner",
     "short": "جارو و تی‌کش رباتیک با نقشه‌برداری لیزری",
     "desc": "جاروی رباتیک شیائومی S10 Plus با ناوبری لیزری LDS و مکش ۴۰۰۰ پاسکال، نقشه دقیق خانه را می‌سازد و با اپلیکیشن کنترل می‌شود.",
     "specs": [("مکش", "۴۰۰۰ پاسکال"), ("باتری", "۵۲۰۰ میلی‌آمپر / ۲۰۰ دقیقه"), ("ناوبری", "لیزری LDS"), ("کنترل", "اپلیکیشن اختصاصی")]},
    {"slug": "philips-ac2930", "name": "تصفیه هوا فیلیپس مدل AC2930 سری ۳۰۰۰i",
     "category": "air-purifiers", "brand": "philips", "price": 10600000, "stock": 16,
     "featured": False, "bestseller": False, "days_old": 62, "img_count": 1,
     "subject": "a tall white modern air purifier appliance",
     "short": "پوشش ۱۰۴ متر مربع با فیلتر HEPA",
     "desc": "تصفیه هوا فیلیپس سری ۳۰۰۰i با فیلتر HEPA H13، ۹۹.۹۵٪ ذرات معلق را حذف می‌کند. سنسور کیفیت هوا، رنگ محیط را نمایش می‌دهد.",
     "specs": [("پوشش", "تا ۱۰۴ متر مربع"), ("فیلتر", "HEPA H13"), ("توان", "۵۰ وات"), ("ویژگی", "سنسور کیفیت هوا")]},
    # ---------------- beauty / wellness ----------------
    {"slug": "braun-series-9-pro", "name": "ریش‌تراش براون مدل Series 9 Pro با پایه شارژ و اتوکلین",
     "category": "shavers", "brand": "braun", "price": 18900000, "stock": 11,
     "featured": False, "bestseller": False, "days_old": 49, "img_count": 1,
     "subject": "a premium electric shaver with a charging station",
     "short": "اصلاح دقیق با تیغه‌های پرو و موتور ۱۰۰۰۰ دور",
     "desc": "براون سری ۹ پرو با تیغه‌های نوآورانه و موتور ۱۰۰۰۰ دور، اصلاحی نزدیک و راحت را حتی روی ریش سه‌روزه ارائه می‌دهد. پایه اتوکلین همه‌روزه تمیز می‌کند.",
     "specs": [("موتور", "۱۰۰۰۰ دور"), ("باتری", "۶۰ دقیقه"), ("ویژگی", "پایه شارژ + اتوکلین"), ("مقاومت", "ضدآب ۱۰۰٪")]},
    {"slug": "masager-geravi", "name": "ماساژور گردنی شارژی مدل Relax Pro با گرمای ملایم",
     "category": "massagers", "brand": None, "price": 2450000, "stock": 25,
     "featured": False, "bestseller": False, "days_old": 68, "img_count": 1,
     "subject": "a u-shaped neck massager device in white-grey",
     "short": "ماساژ گردن و شانه با ۶ حالت و گرمای ملایم",
     "desc": "ماساژور گردنی Relax Pro با ۶ حالت ماساژ و عملکرد گرما، خستگی گردن و شانه را برطرف می‌کند. شارژ USB و طراحی سبک برای استفاده روزمره.",
     "specs": [("حالت‌ها", "۶ حالت ماساژ"), ("گرما", "۳۸-۴۲ درجه"), ("باتری", "داخلی قابل شارژ"), ("وزن", "۹۰۰ گرم")]},
    # ---------------- sports ----------------
    {"slug": "xiaomi-scooter-4-pro", "name": "اسکوتر برقی شیائومی مدل Electric Scooter 4 Pro",
     "category": "bikes-scooters", "brand": "xiaomi", "price": 27900000, "sale": 26500000, "stock": 6,
     "featured": False, "bestseller": False, "days_old": 22, "img_count": 1,
     "subject": "a modern electric kick scooter in dark grey",
     "short": "برد ۵۵ کیلومتر با موتور ۷۰۰ وات",
     "desc": "اسکوتر برقی شیائومی ۴ پرو با موتور ۷۰۰ وات و برد تئوریک ۵۵ کیلومتر، رفت‌وآمد شهری را آسان می‌کند. تایرهای ۱۰ اینچی و ترمز دیسکی دوگانه ایمنی را افزایش می‌دهد.",
     "specs": [("موتور", "۷۰۰ وات"), ("برد", "تا ۵۵ کیلومتر"), ("سرعت", "۲۵ کیلومتر بر ساعت"), (" وزن", "۱۷ کیلوگرم")]},
    # ---------------- fashion ----------------
    {"slug": "nike-backpack-brasilia", "name": "کوله‌پشتی ورزشی نایک مدل Brasilia ظرفیت ۲۵ لیتر",
     "category": "bags", "brand": "nike", "price": 2190000, "stock": 48,
     "featured": False, "bestseller": False, "days_old": 75, "img_count": 1,
     "subject": "a black sporty backpack with subtle texture detail",
     "short": "کوله سبک و مقاوم برای باشگاه و روزمره",
     "desc": "کوله‌پشتی نایک برازیلیا با پارچه مقاوم به آب و بندهای مشبک تنفس‌پذیر، همراهی راحت برای باشگاه و سفرهای روزانه است.",
     "specs": [("ظرفیت", "۲۵ لیتر"), ("جنس", "پلی‌استر مقاوم"), ("ویژگی", "جیب جدا برای کفش"), ("ابعاد", "۴۸×۳۰×۱۸ سانتی‌متر")]},
]

VARIANTS = {
    "iphone-16-pro-max": [
        ("۲۵۶ گیگابایت - تیتانیوم طبیعی", "IP16PM-256-TN", 92000000, 6),
        ("۲۵۶ گیگابایت - تیتانیوم آبی", "IP16PM-256-BL", 92500000, 4),
        ("۵۱۲ گیگابایت - تیتانیوم طبیعی", "IP16PM-512-TN", 106500000, 4),
    ],
    "macbook-air-m3-13": [
        ("۸ گیگابایت / ۵۱۲ گیگابایت - نقره‌ای", "MBA13-M3-8-512-SV", 74500000, 5),
        ("۱۶ گیگابایت / ۵۱۲ گیگابایت - خاکستری", "MBA13-M3-16-512-GR", 82900000, 4),
    ],
    "galaxy-s24-ultra": [
        ("۲۵۶ گیگابایت - تیتانیوم مشکی", "S24U-256-BK", 58500000, 9),
        ("۵۱۲ گیگابایت - تیتانیوم خاکستری", "S24U-512-GR", 63200000, 9),
    ],
}

REVIEWS = {
    "iphone-16-pro-max": [
        ("سارا محمدی", "بهترین گوشی‌ای که داشتم", "کیفیت دوربین فوق‌العاده‌ست و باتری برای یک روز کامل کافیه. ارسال هم سریع بود.", 5),
        ("امیر رضایی", "ارزش خرید بالا", "از ۱۳ پرو آپگرید کردم، صدای اسپیکر و کیفیت ساخت تفاوت واضحی داره.", 5),
        ("نگار کریمی", "خوب اما گرون", "گوشی عالیه ولی قیمتش بالاست. خودِ خرید از این سایت تجربه خوبی بود.", 4),
    ],
    "galaxy-s24-ultra": [
        ("محمد حسینی", "زوم ۲۰۰ مگاپیکسل باورنکردنیه", "برای عکاسی حرفه‌ای عالیه، قلم هم خیلی کاربردیه.", 5),
        ("پریسا نادری", "نمایشگر درخشان", "زیر نور آفتاب هم کاملاً واضحه. بسته‌بندی سالم رسید.", 5),
    ],
    "xiaomi-14t-pro": [
        ("رضا شریفی", "بهترین انتخاب اقتصادی", "با این قیمت عملکردی در حد پرچمدارها داره. شارژ سریعش معرکه‌ست.", 5),
        ("الهام قاسمی", "دوربین لایکا عالی", "عکس‌های شب خیلی خوب می‌شن. دستم گرم نمی‌کنه.", 4),
    ],
    "airpods-pro-2": [
        ("آرش تهرانی", "نویز کنسلینگ فوق‌العاده", "توی مترو هیچ صدایی نمی‌شنوم! کیفیت صدا هم بی‌نظیره.", 5),
        ("مینا احمدی", "راحتی و کیفیت", "خیلی سبکه و توی گوش نمی‌افته. کیس شارژ مرتبه.", 5),
        ("حامد نوری", "عالی", "برای مک و آیفون هماهنگی کامل داره.", 5),
    ],
    "sony-wh-1000xm5": [
        ("کیانا مرادی", "بهترین هدفون بازار", "نویز کنسلینگش از هر هدفونی که داشتم بهتره و راحتیش عالیه.", 5),
        ("سامان رستمی", "برای پرواز عالیه", "باتری واقعاً ۳۰ ساعت جواب میده. کیف حمل خوبی هم داره.", 5),
    ],
    "playstation-5-slim": [
        ("علیرضا کریمی", "تجربه بازی نسل جدید", "سرعت لود بازی‌ها باورنکردنیه. کنترلر دالسنس حس متفاوتی داره.", 5),
        ("بهنام صادقی", "ارسال سریع", "دو روزه رسید، پلمپ و سالم. الان وقت بازی کردنه!", 5),
    ],
    "apple-watch-ultra-2": [
        ("سحر عبدی", "برای ورزش حرفه‌ای", "باتریش برای دوی ماراتن کافیه و نمایشگر زیر نور خورشید هم واضحه.", 5),
        ("کوروش جمشیدی", "تیتانیوم واقعیه", "وزنش محسوسه ولی کیفیت ساخت فوق‌العاده‌ست.", 4),
    ],
    "dyson-v12-detect": [
        ("فاطمه یوسفی", "نظافت خانه متحول شد", "لامپ لیزر گرد و خاک نامرئی رو نشون میده! مکشش خیلی قویه.", 5),
        ("بابک رحیمی", "سبک و قوی", "برای ماکرو و فرش عالیه، جمع کردنش هم راحته.", 5),
    ],
    "delonghi-dedica-ec685": [
        ("شیرین مهدوی", "اسپرسوی کافه‌ای در خانه", "کرما و طعمش حرف نداره. طراحی باریکش روی کابینت جا میشه.", 5),
        ("نوید پارسا", "ارزش خرید", "با ۱۵ بار فشار، تفاوتش با دستگاه‌های ارزون کاملاً مشخصه.", 4),
    ],
    "xiaomi-smart-band-9": [
        ("هستی کاظمی", "سبک و کاربردی", "برای پایش خواب و قدم‌ها عالیه و باتریش واقعاً ۲۰ روزه.", 5),
    ],
    "logitech-mx-master-3s": [
        ("پویا اسدی", "برای کار حرفه‌ای", "اسکرول MagSpeed توی اکسل معجزه می‌کنه. ارگونومی عالی.", 5),
        ("مریم سلطانی", "دست درد نمی‌گیره", "بعد از ساعت‌ها کار با کامپیوتر، دیگه مچ دستم درد نمی‌گیره.", 5),
    ],
    "philips-airfryer-xxl": [
        ("زهرا امینی", "سیب‌زمینی بدون روغن!", "بچه‌ها عاشقش شدن و مصرف روغن خونه نصف شد. تمیز کردنش هم آسونه.", 5),
    ],
    "xiaomi-robot-vacuum-s10": [
        ("اکبر ولیزاده", "نقشه‌برداری دقیق", "با اپ کنترلش می‌کنم، توی خانه کثیف کاری هم نمی‌کنه.", 5),
        ("لیدا فرهادی", "برای حیوانات خونگی", "موی گربه رو خوب جمع می‌کنه. صداش کمه.", 4),
    ],
    "jbl-charge-5": [
        ("سیاوش کیانی", "قدرت صدای باورنکردنی", "برای بیرون و پارتی عالیه و ضدآب بودنش خیال‌آسوده.", 5),
    ],
    "macbook-air-m3-13": [
        ("آیدا نقیبی", "سبک و بی‌صدا", "برای طراحی و کار روزمره بی‌نقصه. بدنه‌اش خوش‌دسته.", 5),
        ("فربد رضایی", "باتری عالی", "یک روز کامل کار می‌کنم بدون شارژر. صفحه‌اش هم عالیه.", 5),
    ],
    "ipad-air-11-m2": [
        ("نیلوفر احمدی", "برای دانشجوها عالیه", "با اپل پنسیل یادداشت‌برداری می‌کنم. وزنش سبکه و راحت حمل میشه.", 5),
    ],
    "galaxy-tab-s9-fe": [
        ("یاسر محمودی", "خوب و کامل", "برای فیلم دیدن و وب‌گردی انتخاب خوبیه. قلمش هم همراهشه.", 4),
    ],
    "xiaomi-scooter-4-pro": [
        ("دانیال عزیزی", "رفت‌وآمد شهری راحت", "برای شرکت رفتن دیگه ترافیک نمی‌بینم. ترمزش مطمئنه.", 5),
    ],
    "braun-series-9-pro": [
        ("شاهین عباسی", "اصلاح بدون تحریک", "پوستم حساسه ولی با این ریش‌تراش هیچ سوزشی ندارم.", 5),
    ],
}

DEMO_ORDERS = {"count": 160, "days": 90}
