# Generated by Django 5.2.17 on 2026-09-20 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '۱ ستاره - بسیار ضعیف'), (2, '۲ ستاره - ضعیف'), (3, '۳ ستاره - معمولی'), (4, '۴ ستاره - خوب'), (5, '۵ ستاره - عالی')], default=5, verbose_name='امتیاز (۱ تا ۵)')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دیدگاه')),
                ('comment', models.TextField(verbose_name='متن دیدگاه')),
                ('is_verified_buyer', models.BooleanField(default=False, verbose_name='خریدار تأیید شده')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تأیید شده برای انتشار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه و امتیاز',
                'verbose_name_plural': 'دیدگاه\u200cها و امتیازها',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_user_product_review')],
            },
        ),
    ]
