# Generated by Django 5.2.17 on 2026-09-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگوی برند')),
                ('description', models.TextField(blank=True, verbose_name='درباره برند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی (مثلاً رنگ، ظرفیت)')),
            ],
            options={
                'verbose_name': 'ویژگی کالا',
                'verbose_name_plural': 'ویژگی\u200cهای کالا',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='اسلاگ (URL)')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='کلاس آیکون یا کاراکتر SVG')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان سئو (Title)')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات سئو (Meta Description)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=250, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=270, unique=True, verbose_name='اسلاگ محصول')),
                ('sku', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='شناسه کالا (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=60, verbose_name='بارکد کالا')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل و بررسی محصول')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت پایه (تومان)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت با تخفیف (تومان)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال در سایت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش\u200cترین')),
                ('is_new_arrival', models.BooleanField(default=False, verbose_name='جدیدترین')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن (گرم/کیلوگرم)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='ابعاد (طول x عرض x ارتفاع)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا سئو')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('value', models.CharField(max_length=150, verbose_name='مقدار ویژگی')),
                ('color_code', models.CharField(blank=True, max_length=20, verbose_name='کد رنگ هگز (مثلاً #FF0000 برای رنگ\u200cها)')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productattribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(upload_to='products/', verbose_name='فایل تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین (Alt Text)')),
                ('is_feature', models.BooleanField(default=False, verbose_name='تصویر اصلی / کاور')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order', '-is_feature', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('key', models.CharField(max_length=150, verbose_name='عنوان مشخصه (مثلاً نوع پردازنده)')),
                ('value', models.CharField(max_length=300, verbose_name='مقدار مشخصه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه فنی محصول',
                'verbose_name_plural': 'مشخصات فنی محصول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان تنوع (مثلاً رنگ مشکی - حافظه ۲۵۶ گیگابایت)')),
                ('sku', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='شناسه اختصاصی (SKU)')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت اختصاصی تنوع (در صورت خالی بودن، قیمت پایه محصول اعمال می\u200cشود)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی این تنوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('attribute_values', models.ManyToManyField(blank=True, related_name='variants', to='catalog.productattributevalue', verbose_name='مقادیر ویژگی\u200cها')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='محصول مرجع')),
            ],
            options={
                'verbose_name': 'تنوع محصول (Variant)',
                'verbose_name_plural': 'تنوع\u200cهای محصولات',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='catalog_pro_is_acti_f6baa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
