# Generated by Django 5.2.17 on 2026-09-20 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'درصدی'), ('FIXED', 'مبلغ ثابت (تومان)')], default='PERCENTAGE', max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار تخفیف (درصد یا تومان)')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='حداکثر سقف تخفیف (برای درصدی)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع اعتبار')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان اعتبار')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد کل استفاده')),
                ('usage_per_user', models.PositiveIntegerField(default=1, verbose_name='حداکثر دفعات استفاده برای هر کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order_number', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='شماره سفارش')),
                ('shipping_name', models.CharField(max_length=150, verbose_name='نام گیرنده')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='شماره تماس گیرنده')),
                ('shipping_province', models.CharField(max_length=100, verbose_name='استان')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='شهر')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('shipping_address_line', models.TextField(verbose_name='نشانی کامل پستی')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع اقلام (تومان)')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ تخفیف (تومان)')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال (تومان)')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مالیات (تومان)')),
                ('grand_total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ نهایی فاکتور (تومان)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('AWAITING_PAYMENT', 'درگاه پرداخت'), ('PAID', 'پرداخت شده و تایید شده'), ('PROCESSING', 'در حال آماده\u200cسازی و بسته\u200cبندی'), ('SHIPPED', 'تحویل به شرکت حمل و نقل'), ('DELIVERED', 'تحویل داده شده به مشتری'), ('CANCELLED', 'لغو شده'), ('RETURNED', 'مرجوع شده'), ('REFUNDED', 'استرداد وجه انجام شد')], db_index=True, default='PENDING', max_length=30, verbose_name='وضعیت سفارش')),
                ('shipping_method', models.CharField(default='پست پیشتاز', max_length=100, verbose_name='روش ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری پستی')),
                ('customer_notes', models.TextField(blank=True, verbose_name='یادداشت خریدار')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای داخلی مدیر')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='کوپن استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.coupon', verbose_name='کوپن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'لاگ استفاده از کوپن',
                'verbose_name_plural': 'لاگ\u200cهای استفاده از کوپن',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product_name', models.CharField(max_length=250, verbose_name='نام محصول در زمان خرید')),
                ('variant_name', models.CharField(blank=True, max_length=200, verbose_name='عنوان تنوع در زمان خرید')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد (تومان)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='جمع سطر (تومان)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ['id'],
            },
        ),
    ]
